# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_  
  - model: vit.yaml
  - paths: default.yaml
  # experiment configs allow to config any model hyperparams while inference
  # e.g. image size or num classes
  - experiment: null

# task name, determines output directory path
task_name: "predict"

# set False to skip model training
train: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

predict: True

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_dir: ${hydra:runtime.cwd}/logs/
ckpt_file: train/runs/2023-08-05_18-44-30/checkpoints/last.ckpt # 2023-06-23/21-03-48/checkpoints/last.ckpt           
test_ckpt_path: ${ckpt_dir}/${ckpt_file}

test_path: ${paths.data_dir}/PetImages_split/test/Cat/42.jpg

# seed for random number generators in pytorch, numpy and python.random
seed: null